### ISSUE TITLE
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by kooshyarkosari** [zhangyp15/MonoFlex#54]
Dear Author
Thank you very much for your excellent and amazing work:
I have tried to replicate the task but got a flowing error during training.
![Screenshot (82)](https://user-images.githubusercontent.com/46442936/216141700-f6386c10-5ee6-4887-8131-5f30eb949d4a.png)

**Comment by Senwang98** [comment]
@kooshyarkosari 
I meet the same problem too.
I commented out the code of 3D iou calculation and it worked well.

**Comment by Senwang98** [comment]
@kooshyarkosari 
I fixed all env problem in MonoFlex.
For this problem, please use `pip install shapely==1.8.4` instead of shapely>=2.0.0.
If you meet problem about `numba.gpu`, please using `numba==0.53`.

If you use RTX30 GPU, you need to replace DCNv2 with other version DCNv2.
If you use RTX40 GPU, for faster training, please using CUDA 11.8.

**Comment by kooshyarkosari** [comment]
@Senwang98 

Thank you so much  the problem has been solved  based on your recommendations,
